!  Fortran Console Application 
!  Generated by PGI Visual Fortran(R)
!  12/3/2014 8:28:38 PM
!  Developed by XUYUAN LI

!  Base on Li, X., Zecchin, A.C., Maier, H.R., 2014b. 
!  Improving Partial Mutual Information-based input variable selection by consideration of boundary issues associated with bandwidth estimation. 
!  Environmental Modelling and Software, submitted on 04/12/2014.

      program PMIIVS_2014

      use GLS                        !General functions
      use PMI1,only:PMIBM1           !PMIB1 (MI:GRR; RE:GRNN(GRR))
      use PMI2,only:PMIBM2           !PMIB2 (MI:DPI; RE:GRNN(GRR))
      use PMI3,only:PMIRELLP         !PMIR5 (MI:DPI; RE:LLP(SVO))
      use PMI4,only:PMIREANN         !PMIR7 (MI:DPI; RE:MLPANN(0 to 3HN))
  
      implicit none
      
      !1.Variables
      real(8),allocatable::allinput(:,:),alloutput(:)  !All inputs & output
      real(8),allocatable::inputx(:,:),outputy(:)      !Inputs & output for each test (e.g. 30 IV)
      real(8),allocatable::inputxs(:,:),outputys(:)    !scaled/standardised data
      real(8),allocatable::t(:,:)                      !recording all computational time
      integer(8)::row,col                              !Row (no. of data), columns (no. of inputs)
      integer(8)::c1,c2,c3,c4,c5,c6,c7,c8,c9,c10       !Counters
      real(8)::t1,t2                                   !Computational time (starting & ending time)
      character(len=22),allocatable::fn(:)             !File name (For all detail results)
      character(len=23),allocatable::fns(:)            !File name (For all summary results) 
      character(len=19),allocatable::fnh(:)            !File name (For all smoothing parameter results) 
      character(len=1)::fn1                            !File # (For all detail results) 
      
      integer(8)::a1,a2                                !*No. of testing methods:e.g 6 ;no. of repeatings: e.g 30 (User can change them here)
      write(*,*)"Please choose the appropriate method for PMIIVS suggested below"
      write(*,*)"Type: 1 for Gaussian and linear/non-linear problem"
      write(*,*)"Type: 2 for slightly to mordately non-Gaussian and linear/norn-linear problem"
      write(*,*)"Type: 3 for extremely non-Gaussian and linear problem"
      write(*,*)"Type: 4 for extremely non-Gaussian and non-linear problem"
      
      read(*,*)a1
      
      write(*,*)"Please choose the no. of repeating tests (e.g. 30)"
      read(*,*)a2

      !2.Generate output files  
      allocate(fn(a1))    !changable e.g. 5 different bandwidth algorithms (1)
      allocate(fns(a1))   !changable e.g. 5 different bandwidth algorithms (2)
      allocate(fnh(a1))   !changable e.g. 5 different bandwidth algorithms (2)
      allocate(t(a2,a1))  !changable e.g. 5 different bandwidth algorithms, 30 IV  (3), (1)
      
         c3=a1          !changable e.g. 5 different bandwidth algorithms (4)                                       
         write(fn1,'(I1)')c3
         fn(c3)="Test_detailoutput"//trim(fn1)//".txt"  !File name for detail results
         fns(c3)="Test_summaryoutput"//trim(fn1)//".txt"  !File name for summary results
         fnh(c3)="Test_KSMICEval"//trim(fn1)//".txt"  !File name for summary results
         c4=199+c3    !File code
         c9=299+c3    !File code
         c10=399+c3   !File code
         open (unit=c4,file=fn(c3),status='replace')  !detail results
         open (unit=c9,file=fns(c3),status='replace')  !summary results
         open (unit=c10,file=fnh(c3),status='replace')  !summary results
     
      
      !3.Numerical analysis
      !3.1 Load from input file  
      open (unit=111,file="EAR4_NORM.txt",status='old') !Load input file; EAR4_NORM
      read(111,*)row,col
      allocate(allinput(row,col))
      allocate(alloutput(row))
      do c1=1,row
         read(111,*)(allinput(c1,c2),c2=1,col),alloutput(c1)
      end do
      c6=row/a2                                            
      allocate(inputx(c6,col)) 
      allocate(outputy(c6)) 
      allocate(inputxs(c6,col)) 
      allocate(outputys(c6)) 
      
      !3.2 Generate output file  
         c3=a1       
         c9=299+c3
         write(c9,'(3A9)')"AICp","ORD","PMI" !Criteria

         c3=a1       
         c10=399+c3
         write(c10,'(A20)')"Bandwidth parameter & K-S D:"  
           
      !3.3 Tests  
 do c5=1,a2      
    write(*,'(A13,I2,X,A15)')"*****TEST No.",c5,"processing*****"                                      
    
       c3=a1          
       c4=199+c3
       write(c4,*)
       write(c4,'(A13,I2,X,A15)')"*****TEST No.",c5,"processing*****"   

       c3=a1         
       c10=399+c3
       write(c10,*)
       write(c10,'(A13,I2,X,A15)')"*****TEST No.",c5,"processing*****"   

        c3=a1          
        do c2=1,col    
           c7=(c5-1)*row/a2  
           do c1=1,c6
              c8=c7+c1
              inputx(c1,c2)=allinput(c8,c2)
           end do
        end do
        
        c7=(c5-1)*row/a2                                
        do c1=1,c6
           c8=c7+c1
           outputy(c1)=alloutput(c8)
        end do      
        
        !standardised data
        do c2=1,col
           call scaling(inputx(1:c6,c2),c6,inputxs(1:c6,c2))
           !call sdf(inputx(1:c6,c2),c6,inputxs(1:c6,c2))
        end do
           call scaling(outputy(1:c6),c6,outputys(1:c6))
           !call sdf(outputy(1:c6),c6,outputys(1:c6))
            
        call CPU_time(t1)
        if (c3==1) then
            call PMIBM1(inputxs,outputys,c6,col) !Results summary (MI:GRR; RE:GRNN(GRR))
        else if (c3==2) then     
            call PMIBM2(inputxs,outputys,c6,col) !Results summary (MI:DPI; RE:GRNN(GRR))
        else if (c3==3) then     
            call PMIRELLP(inputxs,outputys,c6,col) !Results summary (MI:DPI; RE:LLP(SVO))
        else 
            call PMIREANN(inputxs,outputys,c6,col) !Results summary (MI:DPI; RE:MLPANN(0 to 3HN))     
        end if                                  
        
        call CPU_time(t2)
        t(c5,c3)=t2-t1
        c4=199+c3
        write(c4,'(A26,F9.2,A1)')"The computational time is:",t(c5,c3),"s"    
     
end do 

     !3.4 Write outputs (CT)
         c3=a1             !changable e.g. 5 different bandwidth algorithms (8)
         c9=299+c3 
         write(c9,'(A4)')"Time" 
         do c5=1,a2          !changable e.g. 30 IV  (6)
            write(c9,'(F9.4)')t(c5,c3)
         end do
 
        
      !4.Ending
      close(111)
      c3=a1            !changable e.g. 5 different bandwidth algorithms (9)
         c4=199+c3
         close(c4)
  
      
      c3=a1            !changable e.g. 5 different bandwidth algorithms (10)
         c9=299+c3
         close(c9)

      
      c3=a1            !changable e.g. 5 different bandwidth algorithms (10)
         c10=399+c3
         close(c10)

      
      deallocate(fn) 
      deallocate(fns) 
      deallocate(fnh)
      deallocate(allinput)
      deallocate(alloutput)
      deallocate(inputxs) 
      deallocate(outputys) 
      deallocate(inputx)
      deallocate(outputy)
      deallocate(t) 

      end program PMIIVS_2014
